import { StyleSheet } from "react-native";
import { Color, FontFamily } from "@/styles/GlobalStyle";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Color.background,
  },
  scrollContent: {
    flexGrow: 1,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 4,
  },
  headerTopMeta: {
    width: "100%",
  },
  ornamentWrap: {
    marginHorizontal: 20,
    marginBottom: 4,
    marginTop: 8,
  },
  floatingTimerWrap: {
    position: "absolute",
    top: 8,
    left: 16,
    zIndex: 46,
  },
  floatingBattleWrap: {
    position: "absolute",
    top: 8,
    right: 16,
    zIndex: 46,
  },
  progressHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 4,
    marginBottom: 4,
  },
  progressCounter: {
    marginTop: 6,
    paddingHorizontal: 4,
    fontFamily: FontFamily.interMedium,
    fontSize: 12,
    color: Color.colorSlategray,
  },
  progressSyncText: {
    marginTop: 6,
    paddingHorizontal: 4,
    fontFamily: FontFamily.interMedium,
    fontSize: 11,
    color: Color.colorSlategray,
  },
  progressLabel: {
    flex: 1,
    minWidth: 0,
    fontFamily: FontFamily.interMedium,
    fontSize: 13,
    color: Color.colorAliceblue300,
  },
  progressPercent: {
    flexShrink: 0,
    fontFamily: FontFamily.poppinsExtraBold,
    fontSize: 13,
    color: Color.colorAliceblue,
  },
  progressBarContainer: {
    width: "100%",
    maxWidth: "100%",
    alignSelf: "stretch",
    height: 12,
    backgroundColor: Color.colorDarkslategray100,
    borderRadius: 999,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: Color.colorAliceblue100,
  },
  skipContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  skipButton: {
    backgroundColor: "rgba(255, 193, 7, 0.15)",
    borderWidth: 1,
    borderColor: "#FFC107",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  skipButtonText: {
    fontFamily: FontFamily.interMedium,
    fontSize: 14,
    color: "#FFC107",
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  helperText: {
    fontFamily: FontFamily.interMedium,
    fontSize: 14,
    color: Color.colorSlategray,
    textAlign: "center",
  },
  errorTitle: {
    fontFamily: FontFamily.inikaBold,
    fontSize: 18,
    color: "salmon",
    marginBottom: 6,
  },
  card: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Color.colorDarkslategray100,
    backgroundColor: "#161f3d",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    gap: 6,
  },
  cardFileFocus: {
    paddingTop: 12,
    paddingBottom: 12,
    gap: 3,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardHeaderFileFocus: {
    marginBottom: 0,
  },
  tag: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  tagFileFocus: {
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  tagText: {
    fontFamily: FontFamily.interMedium,
    fontSize: 12,
    letterSpacing: 0.3,
  },
  progressChip: {
    fontFamily: FontFamily.interMedium,
    fontSize: 12,
    color: Color.colorSlategray,
  },
  cardTitle: {
    fontFamily: FontFamily.inikaBold,
    fontSize: 16,
    color: Color.colorAliceblue,
    marginBottom: 4,
  },
  cardTitleFileFocus: {
    fontSize: 14,
    marginBottom: 1,
  },
  cardType: {
    fontFamily: FontFamily.interMedium,
    fontSize: 12,
    color: Color.colorSlategray,
    marginBottom: 8,
  },
  cardTypeFileFocus: {
    fontSize: 11,
    marginBottom: 3,
  },
  footer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    backgroundColor: Color.background,
    borderTopWidth: 1,
    borderTopColor: Color.colorDarkslategray100,
    position: "relative",
    zIndex: 30,
    elevation: 18,
  },
  footerRow: {
    flexDirection: "row",
    gap: 10,
  },
  button: {
    flex: 1,
    minHeight: 56,
    paddingVertical: 12,
    backgroundColor: Color.colorDarkslategray100,
    borderWidth: 1,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 56,
    paddingVertical: 12,
    backgroundColor: Color.colorDarkslategray200,
    borderWidth: 1,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    fontFamily: FontFamily.inikaBold,
    fontSize: 15,
    color: Color.colorWhite,
  },
  secondaryButtonText: {
    fontFamily: FontFamily.inikaBold,
    fontSize: 15,
    color: Color.colorAliceblue,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#1b2340",
    borderRadius: 16,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: Color.colorDarkslategray100,
  },
  modalTitle: {
    fontFamily: FontFamily.inikaBold,
    fontSize: 18,
    color: Color.colorAliceblue,
  },
  modalIcon: {
    fontSize: 20,
  },
  modalSubtitle: {
    fontFamily: FontFamily.interMedium,
    fontSize: 13,
    color: Color.colorSlategray,
  },
  modalOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Color.colorDarkslategray100,
    backgroundColor: "#131a34",
  },
  modalOptionTitle: {
    fontFamily: FontFamily.inikaBold,
    fontSize: 15,
    color: Color.colorAliceblue,
  },
  modalOptionDesc: {
    fontFamily: FontFamily.interMedium,
    fontSize: 12,
    color: Color.colorSlategray,
  },
  modalOptionLink: {
    fontFamily: FontFamily.inikaBold,
    fontSize: 13,
    color: Color.colorAliceblue,
  },
  modalClose: {
    marginTop: 4,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Color.colorDarkslategray100,
    backgroundColor: "#11182f",
  },
  modalCloseText: {
    fontFamily: FontFamily.interMedium,
    fontSize: 14,
    color: Color.colorAliceblue,
  },
});
