import type { ImageSourcePropType } from 'react-native';

// Mesmos IDs do catálogo do professor, persistidos em conteudos.metadata.boss_visual.
export const bossVisuals: Record<string, ImageSourcePropType> = {
  'boss-01': require('../assets/bosses/boss-01.png'),
  'boss-02': require('../assets/bosses/boss-02.png'),
  'boss-03': require('../assets/bosses/boss-03.png'),
  'boss-04': require('../assets/bosses/boss-04.png'),
  'boss-05': require('../assets/bosses/boss-05.png'),
  'boss-06': require('../assets/bosses/boss-06.png'),
  'boss-07': require('../assets/bosses/boss-07.png'),
  'boss-08': require('../assets/bosses/boss-08.png'),
  'boss-09': require('../assets/bosses/boss-09.png'),
  'boss-10': require('../assets/bosses/boss-10.png'),
  'boss-11': require('../assets/bosses/boss-11.png'),
  'boss-12': require('../assets/bosses/boss-12.png'),
  'boss-13': require('../assets/bosses/boss-13.png'),
  'boss-14': require('../assets/bosses/boss-14.png'),
  'boss-15': require('../assets/bosses/boss-15.png'),
  'boss-16': require('../assets/bosses/boss-16.png'),
  'boss-17': require('../assets/bosses/boss-17.png'),
  'boss-18': require('../assets/bosses/boss-18.png'),
  'boss-19': require('../assets/bosses/boss-19.png'),
  'boss-20': require('../assets/bosses/boss-20.png'),
  'boss-21': require('../assets/bosses/boss-21.png'),
  'boss-22': require('../assets/bosses/boss-22.png'),
  'boss-23': require('../assets/bosses/boss-23.png'),
  'boss-24': require('../assets/bosses/boss-24.png'),
  'boss-25': require('../assets/bosses/boss-25.png'),
  'boss-26': require('../assets/bosses/boss-26.png'),
  'boss-27': require('../assets/bosses/boss-27.png'),
  'boss-28': require('../assets/bosses/boss-28.png'),
  'boss-29': require('../assets/bosses/boss-29.png'),
  'boss-30': require('../assets/bosses/boss-30.png'),
  'boss-31': require('../assets/bosses/boss-31.png'),
};
