import type { ImageSourcePropType } from "react-native";
import type { BrainHexProfile } from "./brainHexProfiles";

export const profileUtilityIcons = {
  bag: {
    socializer: require("@/assets/utility-profiles/bag-socializer.png"),
    survivor: require("@/assets/utility-profiles/bag-survivor.png"),
    conqueror: require("@/assets/utility-profiles/bag-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/bag-mastermind.png"),
    achiever: require("@/assets/utility-profiles/bag-achiever.png"),
    seeker: require("@/assets/utility-profiles/bag-seeker.png"),
    daredevil: require("@/assets/utility-profiles/bag-daredevil.png"),
  },
  ranking: {
    socializer: require("@/assets/utility-profiles/achievements-socializer.png"),
    survivor: require("@/assets/utility-profiles/achievements-survivor.png"),
    conqueror: require("@/assets/utility-profiles/achievements-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/achievements-mastermind.png"),
    achiever: require("@/assets/utility-profiles/achievements-achiever.png"),
    seeker: require("@/assets/utility-profiles/achievements-seeker.png"),
    daredevil: require("@/assets/utility-profiles/achievements-daredevil.png"),
  },
  deadline: {
    socializer: require("@/assets/utility-profiles/deadline-socializer.png"),
    survivor: require("@/assets/utility-profiles/deadline-survivor.png"),
    conqueror: require("@/assets/utility-profiles/deadline-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/deadline-mastermind.png"),
    achiever: require("@/assets/utility-profiles/deadline-achiever.png"),
    seeker: require("@/assets/utility-profiles/deadline-seeker.png"),
    daredevil: require("@/assets/utility-profiles/deadline-daredevil.png"),
  },
  store: {
    socializer: require("@/assets/utility-profiles/store-socializer.png"),
    survivor: require("@/assets/utility-profiles/store-survivor.png"),
    conqueror: require("@/assets/utility-profiles/store-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/store-mastermind.png"),
    achiever: require("@/assets/utility-profiles/store-achiever.png"),
    seeker: require("@/assets/utility-profiles/store-seeker.png"),
    daredevil: require("@/assets/utility-profiles/store-daredevil.png"),
  },
  book: {
    socializer: require("@/assets/utility-profiles/book-socializer.png"),
    survivor: require("@/assets/utility-profiles/book-survivor.png"),
    conqueror: require("@/assets/utility-profiles/book-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/book-mastermind.png"),
    achiever: require("@/assets/utility-profiles/book-achiever.png"),
    seeker: require("@/assets/utility-profiles/book-seeker.png"),
    daredevil: require("@/assets/utility-profiles/book-daredevil.png"),
  },
  medal: {
    socializer: require("@/assets/utility-profiles/medal-socializer.png"),
    survivor: require("@/assets/utility-profiles/medal-survivor.png"),
    conqueror: require("@/assets/utility-profiles/medal-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/medal-mastermind.png"),
    achiever: require("@/assets/utility-profiles/medal-achiever.png"),
    seeker: require("@/assets/utility-profiles/medal-seeker.png"),
    daredevil: require("@/assets/utility-profiles/medal-daredevil.png"),
  },
  coin: {
    socializer: require("@/assets/utility-profiles/coin-socializer.png"),
    survivor: require("@/assets/utility-profiles/coin-survivor.png"),
    conqueror: require("@/assets/utility-profiles/coin-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/coin-mastermind.png"),
    achiever: require("@/assets/utility-profiles/coin-achiever.png"),
    seeker: require("@/assets/utility-profiles/coin-seeker.png"),
    daredevil: require("@/assets/utility-profiles/coin-daredevil.png"),
  },
  notifications: {
    socializer: require("@/assets/utility-profiles/notifications-socializer.png"),
    survivor: require("@/assets/utility-profiles/notifications-survivor.png"),
    conqueror: require("@/assets/utility-profiles/notifications-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/notifications-mastermind.png"),
    achiever: require("@/assets/utility-profiles/notifications-achiever.png"),
    seeker: require("@/assets/utility-profiles/notifications-seeker.png"),
    daredevil: require("@/assets/utility-profiles/notifications-daredevil.png"),
  },
  settings: {
    socializer: require("@/assets/utility-profiles/settings-socializer.png"),
    survivor: require("@/assets/utility-profiles/settings-survivor.png"),
    conqueror: require("@/assets/utility-profiles/settings-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/settings-mastermind.png"),
    achiever: require("@/assets/utility-profiles/settings-achiever.png"),
    seeker: require("@/assets/utility-profiles/settings-seeker.png"),
    daredevil: require("@/assets/utility-profiles/settings-daredevil.png"),
  },
  social: {
    socializer: require("@/assets/utility-profiles/social-socializer.png"),
    survivor: require("@/assets/utility-profiles/social-survivor.png"),
    conqueror: require("@/assets/utility-profiles/social-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/social-mastermind.png"),
    achiever: require("@/assets/utility-profiles/social-achiever.png"),
    seeker: require("@/assets/utility-profiles/social-seeker.png"),
    daredevil: require("@/assets/utility-profiles/social-daredevil.png"),
  },
  achievements: {
    socializer: require("@/assets/utility-profiles/achievement-icon-socializer.png"),
    survivor: require("@/assets/utility-profiles/achievement-icon-survivor.png"),
    conqueror: require("@/assets/utility-profiles/achievement-icon-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/achievement-icon-mastermind.png"),
    achiever: require("@/assets/utility-profiles/achievement-icon-achiever.png"),
    seeker: require("@/assets/utility-profiles/achievement-icon-seeker.png"),
    daredevil: require("@/assets/utility-profiles/achievement-icon-daredevil.png"),
  },
  hint: {
    socializer: require("@/assets/utility-profiles/hint-socializer.png"),
    survivor: require("@/assets/utility-profiles/hint-survivor.png"),
    conqueror: require("@/assets/utility-profiles/hint-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/hint-mastermind.png"),
    achiever: require("@/assets/utility-profiles/hint-achiever.png"),
    seeker: require("@/assets/utility-profiles/hint-seeker.png"),
    daredevil: require("@/assets/utility-profiles/hint-daredevil.png"),
  },
  retry: {
    socializer: require("@/assets/utility-profiles/retry-socializer.png"),
    survivor: require("@/assets/utility-profiles/retry-survivor.png"),
    conqueror: require("@/assets/utility-profiles/retry-conqueror.png"),
    mastermind: require("@/assets/utility-profiles/retry-mastermind.png"),
    achiever: require("@/assets/utility-profiles/retry-achiever.png"),
    seeker: require("@/assets/utility-profiles/retry-seeker.png"),
    daredevil: require("@/assets/utility-profiles/retry-daredevil.png"),
  },
} satisfies Record<"bag" | "ranking" | "social" | "achievements" | "deadline" | "store" | "book" | "medal" | "coin" | "notifications" | "settings" | "hint" | "retry", Record<BrainHexProfile, ImageSourcePropType>>;
