-- Loja modal Social por perfil
BEGIN;

CREATE TABLE IF NOT EXISTS public.loja_perfis (
  perfil_id bigint PRIMARY KEY REFERENCES public.perfil(id) ON DELETE CASCADE,
  icon_key text NOT NULL DEFAULT 'storefront-outline',
  theme_key text NOT NULL DEFAULT 'default',
  chest_key text NOT NULL DEFAULT 'treasure-chest',
  accent_color text,
  version integer NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.loja_itens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  section text NOT NULL CHECK (section IN ('informacoes','itens','combos','bonus','presentes')),
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  asset_key text,
  price integer NOT NULL CHECK (price >= 0),
  currency text NOT NULL DEFAULT 'coins',
  gate jsonb,
  item_kind text NOT NULL DEFAULT 'permanent' CHECK (item_kind IN ('permanent','consumable')),
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.loja_saldos (
  aluno_id uuid NOT NULL REFERENCES public.alunos(id) ON DELETE CASCADE,
  currency text NOT NULL DEFAULT 'coins',
  balance integer NOT NULL DEFAULT 0 CHECK (balance >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (aluno_id, currency)
);

CREATE TABLE IF NOT EXISTS public.loja_movimentos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  aluno_id uuid NOT NULL REFERENCES public.alunos(id) ON DELETE CASCADE,
  item_id bigint REFERENCES public.loja_itens(id),
  request_id uuid NOT NULL,
  currency text NOT NULL DEFAULT 'coins',
  amount integer NOT NULL,
  reason text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (aluno_id, request_id)
);

CREATE TABLE IF NOT EXISTS public.loja_posses (
  aluno_id uuid NOT NULL REFERENCES public.alunos(id) ON DELETE CASCADE,
  item_id bigint NOT NULL REFERENCES public.loja_itens(id) ON DELETE CASCADE,
  purchased_at timestamptz NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'store',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (aluno_id, item_id)
);

CREATE INDEX IF NOT EXISTS loja_itens_active_section_idx
  ON public.loja_itens (section, sort_order) WHERE active;
CREATE INDEX IF NOT EXISTS loja_movimentos_aluno_created_idx
  ON public.loja_movimentos (aluno_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.trailup_loja_gate_ok(
  p_aluno_id uuid,
  p_gate jsonb
) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp AS $fn$
  SELECT p_gate IS NULL
    OR (
      COALESCE((
        SELECT sum(e.active_sec)
        FROM (
          SELECT DISTINCT ON (sessao_id, item_key, captured_at, active_sec)
                 active_sec
          FROM public.telemetria_time_metric_entries
          WHERE aluno_id = p_aluno_id
            AND scope = p_gate->>'scope'
            AND captured_at <= now()
          ORDER BY sessao_id, item_key, captured_at, active_sec, id
        ) e
      ), 0) >= COALESCE((p_gate->>'minimum')::numeric, 0)
    );
$fn$;

CREATE OR REPLACE FUNCTION public.trailup_loja_catalogo(p_section text DEFAULT NULL)
RETURNS TABLE (
  id bigint, slug text, section text, name text, description text, asset_key text,
  price integer, currency text, gate jsonb, metadata jsonb, active boolean,
  gate_met boolean, owned boolean
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp AS $fn$
  SELECT i.id, i.slug, i.section, i.name, i.description, i.asset_key, i.price,
         i.currency, i.gate, i.metadata, i.active,
         public.trailup_loja_gate_ok(auth.uid(), i.gate),
         EXISTS (SELECT 1 FROM public.loja_posses p
                  WHERE p.aluno_id = auth.uid() AND p.item_id = i.id)
    FROM public.loja_itens i
   WHERE i.active AND (p_section IS NULL OR i.section = p_section)
   ORDER BY i.sort_order, i.id;
$fn$;

CREATE OR REPLACE FUNCTION public.trailup_comprar_loja_item(
  p_item_id bigint,
  p_request_id uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp AS $fn$
DECLARE
  v_aluno_id uuid := auth.uid();
  v_item public.loja_itens%ROWTYPE;
  v_saldo public.loja_saldos%ROWTYPE;
  v_already boolean;
BEGIN
  IF v_aluno_id IS NULL THEN RAISE EXCEPTION 'unauthenticated'; END IF;
  SELECT * INTO v_item FROM public.loja_itens WHERE id = p_item_id AND active FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'item_unavailable'; END IF;
  IF EXISTS (SELECT 1 FROM public.loja_movimentos WHERE aluno_id = v_aluno_id AND request_id = p_request_id) THEN
    RETURN jsonb_build_object('status','already_processed','item_id',p_item_id);
  END IF;
  IF NOT public.trailup_loja_gate_ok(v_aluno_id, v_item.gate) THEN
    RAISE EXCEPTION 'gate_not_met';
  END IF;
  SELECT * INTO v_saldo FROM public.loja_saldos
   WHERE aluno_id = v_aluno_id AND currency = v_item.currency FOR UPDATE;
  IF NOT FOUND THEN
    INSERT INTO public.loja_saldos(aluno_id, currency, balance)
    VALUES (v_aluno_id, v_item.currency, 0)
    RETURNING * INTO v_saldo;
  END IF;
  SELECT EXISTS (SELECT 1 FROM public.loja_posses WHERE aluno_id=v_aluno_id AND item_id=p_item_id)
    INTO v_already;
  IF v_already AND v_item.item_kind = 'permanent' THEN RAISE EXCEPTION 'already_owned'; END IF;
  IF v_saldo.balance < v_item.price THEN RAISE EXCEPTION 'insufficient_balance'; END IF;
  UPDATE public.loja_saldos SET balance = balance - v_item.price, updated_at = now()
   WHERE aluno_id=v_aluno_id AND currency=v_item.currency;
  INSERT INTO public.loja_movimentos(aluno_id,item_id,request_id,currency,amount,reason)
  VALUES (v_aluno_id,p_item_id,p_request_id,v_item.currency,-v_item.price,'purchase');
  INSERT INTO public.loja_posses(aluno_id,item_id,source)
  VALUES (v_aluno_id,p_item_id,'store')
  ON CONFLICT (aluno_id,item_id) DO UPDATE SET purchased_at=now()
  WHERE v_item.item_kind <> 'permanent';
  RETURN jsonb_build_object('status','purchased','item_id',p_item_id,
    'currency',v_item.currency,'balance',v_saldo.balance-v_item.price);
END;
$fn$;

ALTER TABLE public.loja_perfis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loja_itens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loja_saldos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loja_movimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loja_posses ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.loja_perfis, public.loja_itens TO authenticated;
GRANT SELECT ON public.loja_saldos, public.loja_posses TO authenticated;
GRANT EXECUTE ON FUNCTION public.trailup_loja_catalogo(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.trailup_comprar_loja_item(bigint, uuid) TO authenticated;

DROP POLICY IF EXISTS loja_perfis_select ON public.loja_perfis;
CREATE POLICY loja_perfis_select ON public.loja_perfis FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS loja_itens_select ON public.loja_itens;
CREATE POLICY loja_itens_select ON public.loja_itens FOR SELECT TO authenticated USING (active);
DROP POLICY IF EXISTS loja_saldos_select ON public.loja_saldos;
CREATE POLICY loja_saldos_select ON public.loja_saldos FOR SELECT TO authenticated USING (auth.uid() = aluno_id);
DROP POLICY IF EXISTS loja_posses_select ON public.loja_posses;
CREATE POLICY loja_posses_select ON public.loja_posses FOR SELECT TO authenticated USING (auth.uid() = aluno_id);

COMMIT;
