import { GuildIcon } from "@/assets/social/guild-icons";
import { GuildChatModal, type GuildShareOption } from "@/components/social/GuildChatModal";
import type { Guild } from "@/services/social/guildModel";
import { aceitarConviteGuilda, convidarParaGuilda, criarGuilda, entrarGuilda, recusarConviteGuilda, sairGuilda } from "@/services/social/guildService";
import type { SocialPerson } from "@/services/social/socialModel";
import { FontFamily } from "@/styles/GlobalStyle";
import React, { useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

type Props = { guilds: Guild[]; people: SocialPerson[]; classeId: number; accent: string; profile?: string | null; shareOptions: GuildShareOption[]; onReload: () => Promise<void> };

function actionError(error: unknown) {
  const value = String((error as { message?: unknown })?.message ?? error).toLowerCase();
  if (value.includes("guilda_cheia")) return "Esta guilda já atingiu o limite de 10 pessoas.";
  if (value.includes("janela")) return "A janela de formação está fechada.";
  if (value.includes("membro_existente")) return "Você já participa de uma guilda nesta turma.";
  return "Não foi possível concluir a ação.";
}

export function GuildSection({ guilds, people, classeId, accent, profile, shareOptions, onReload }: Props) {
  const [creating, setCreating] = useState(false);
  const [name, setName] = useState("");
  const [busy, setBusy] = useState<string | null>(null);
  const [chatGuild, setChatGuild] = useState<Guild | null>(null);
  async function run(id: string, operation: () => Promise<unknown>) { setBusy(id); try { await operation(); await onReload(); } catch (error) { Alert.alert("Guildas", actionError(error)); } finally { setBusy(null); } }
  const invites = guilds.flatMap((guild) => guild.convitesRecebidos.map((invite) => ({ invite, guild })));
  function inviteCandidates(guild: Guild) { const memberIds = new Set(guild.membros.map((member) => member.alunoId)); return people.filter((person) => !memberIds.has(person.alunoId) && person.status !== "blocked"); }
  return <View style={s.root}>
    <View style={s.heading}><View><Text style={[s.title, { color: accent }]}>GUILDAS</Text><Text style={s.subtitle}>Equipes de até 10 pessoas.</Text></View><GuildIcon color={accent} size={38} /></View>
    {invites.map(({ invite, guild }) => <View key={invite.id} style={s.invite}><Text style={s.inviteText}>Convite para entrar em <Text style={s.name}>{guild.nome}</Text></Text><View style={s.formActions}><Pressable onPress={() => run(invite.id, () => recusarConviteGuilda(invite.id))} style={s.secondary}><Text style={s.secondaryText}>Recusar</Text></Pressable><Pressable onPress={() => run(invite.id, () => aceitarConviteGuilda(invite.id))} style={[s.primary, { backgroundColor: accent }]}><Text style={s.primaryText}>Aceitar</Text></Pressable></View></View>)}
    {guilds.length === 0 ? <View style={s.empty}><Text style={s.emptyText}>Nenhuma guilda criada nesta turma.</Text><Pressable onPress={() => setCreating(true)} style={[s.primary, { backgroundColor: accent }]}><Text style={s.primaryText}>Criar guilda</Text></Pressable></View> : guilds.map((guild) => <View key={guild.id} style={s.card}><View style={s.cardTop}><GuildIcon color={accent} /><View style={s.cardInfo}><Text style={s.name}>{guild.nome}</Text><Text style={s.meta}>{guild.membrosAtivos}/{guild.limiteMembros} membros</Text></View></View>{guild.descricao ? <Text style={s.description}>{guild.descricao}</Text> : null}<View style={s.memberList}>{guild.membros.slice(0, 10).map((member) => <Text key={member.alunoId} style={s.member}>• {member.nome}</Text>)}</View>{guild.souCriador && inviteCandidates(guild).length > 0 ? <View style={s.invites}><Text style={s.inviteLabel}>COLEGAS DA TURMA</Text>{inviteCandidates(guild).map((person) => <View key={person.alunoId} style={s.personRow}><Text numberOfLines={1} style={s.personName}>{person.apelido || person.nome}</Text><Pressable onPress={() => run(person.alunoId, () => convidarParaGuilda(guild.id, person.alunoId))} style={[s.smallAction, { borderColor: accent }]}><Text style={[s.smallActionText, { color: accent }]}>Convidar</Text></Pressable></View>)}</View> : null}{guild.souMembro ? <><Pressable onPress={() => setChatGuild(guild)} style={[s.chatButton, { borderColor: accent }]}><Text style={[s.chatButtonText, { color: accent }]}>Abrir conversa</Text></Pressable><Pressable disabled={busy === guild.id} onPress={() => run(guild.id, () => sairGuilda(guild.id))} style={s.secondary}><Text style={s.secondaryText}>{busy === guild.id ? "..." : "Sair da guilda"}</Text></Pressable></> : guild.membrosAtivos < guild.limiteMembros ? <Pressable disabled={busy === guild.id} onPress={() => run(guild.id, () => entrarGuilda(guild.id))} style={[s.primary, { backgroundColor: accent }]}><Text style={s.primaryText}>{busy === guild.id ? "..." : "Entrar na guilda"}</Text></Pressable> : <Text style={s.full}>Guilda completa</Text>}</View>)}
    {guilds.length > 0 && !guilds.some((guild) => guild.souMembro) ? <Pressable onPress={() => setCreating(true)} style={s.createLink}><Text style={[s.createText, { color: accent }]}>+ Criar nova guilda</Text></Pressable> : null}
    {creating ? <View style={s.form}><Text style={s.formTitle}>Nova guilda</Text><TextInput accessibilityLabel="Nome da guilda" value={name} onChangeText={setName} placeholder="Nome da guilda" placeholderTextColor="#77758b" style={s.input} maxLength={40} /><View style={s.formActions}><Pressable onPress={() => setCreating(false)} style={s.secondary}><Text style={s.secondaryText}>Cancelar</Text></Pressable><Pressable disabled={!name.trim() || busy === "create"} onPress={() => run("create", async () => { await criarGuilda(classeId, name.trim()); setName(""); setCreating(false); })} style={[s.primary, { backgroundColor: accent }]}><Text style={s.primaryText}>{busy === "create" ? <ActivityIndicator color="#fff" /> : "Criar"}</Text></Pressable></View></View> : null}
    <GuildChatModal visible={chatGuild !== null} guild={chatGuild} accent={accent} profile={profile} options={shareOptions} onClose={() => setChatGuild(null)} />
  </View>;
}

const s = StyleSheet.create({ root: { gap: 12 }, heading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 8 }, title: { fontFamily: FontFamily.poppinsExtraBold, fontSize: 16, letterSpacing: 1 }, subtitle: { color: "rgba(242,247,250,.62)", fontSize: 12, marginTop: 3 }, empty: { alignItems: "center", gap: 14, padding: 28, borderRadius: 14, backgroundColor: "rgba(242,247,250,.08)" }, emptyText: { color: "#c7c5d2", textAlign: "center" }, card: { padding: 15, borderRadius: 14, backgroundColor: "rgba(242,247,250,.08)", gap: 10 }, cardTop: { flexDirection: "row", alignItems: "center", gap: 10 }, cardInfo: { flex: 1 }, name: { color: "#f2f7fa", fontFamily: FontFamily.poppinsExtraBold, fontSize: 15 }, meta: { color: "#9db8ff", fontSize: 11, marginTop: 3 }, description: { color: "#b9b7c7", fontSize: 12 }, memberList: { gap: 3 }, member: { color: "#d8d5df", fontSize: 12 }, invites: { gap: 6, borderTopColor: "rgba(242,247,250,.12)", borderTopWidth: 1, paddingTop: 9 }, inviteLabel: { color: "#9db8ff", fontSize: 10, fontWeight: "800" }, personRow: { alignItems: "center", flexDirection: "row", gap: 8 }, personName: { color: "#d8d5df", flex: 1, fontSize: 12 }, smallAction: { borderRadius: 7, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 5 }, smallActionText: { fontSize: 10, fontWeight: "800" }, chatButton: { alignItems: "center", borderRadius: 9, borderWidth: 1, paddingVertical: 9 }, chatButtonText: { fontFamily: FontFamily.poppinsExtraBold, fontSize: 12 }, invite: { padding: 14, borderRadius: 12, backgroundColor: "rgba(157,184,255,.12)", gap: 10 }, inviteText: { color: "#d8d5df", fontSize: 13 }, primary: { alignItems: "center", borderRadius: 9, paddingHorizontal: 14, paddingVertical: 10 }, primaryText: { color: "#fff", fontFamily: FontFamily.poppinsExtraBold, fontSize: 12 }, secondary: { alignItems: "center", borderColor: "rgba(242,247,250,.3)", borderRadius: 9, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 9 }, secondaryText: { color: "#c7c5d2", fontSize: 12, fontWeight: "700" }, full: { color: "#8f8da3", fontSize: 12, textAlign: "center" }, createLink: { alignItems: "center", padding: 10 }, createText: { fontWeight: "800" }, form: { gap: 10, padding: 15, borderRadius: 14, backgroundColor: "#171638" }, formTitle: { color: "#fff", fontFamily: FontFamily.poppinsExtraBold, fontSize: 15 }, input: { color: "#fff", borderColor: "rgba(242,247,250,.25)", borderRadius: 9, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10 }, formActions: { flexDirection: "row", gap: 10 } });
