import { socialChatListar, socialChatEnviar, socialChatPresenca } from "@/services/social/socialService";
import { FontFamily } from "@/styles/GlobalStyle";
import { getProfileShellPalette } from "@/utils/profileShellTheme";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

type Props = { visible: boolean; person: { alunoId: string; nome: string; apelido: string | null; online?: boolean }; accent: string; profile?: string | null; onClose: () => void };
type Message = { id: string; remetente_id: string; texto: string; created_at: string; remetente_nome: string };

export function PrivateChatModal({ visible, person, accent, profile, onClose }: Props) {
  const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(""); const [online, setOnline] = useState(Boolean(person.online)); const [loading, setLoading] = useState(false); const [sending, setSending] = useState(false); const palette = getProfileShellPalette(profile);
  const load = useCallback(async () => { if (!person) return; try { const [nextMessages, nextOnline] = await Promise.all([socialChatListar(person.alunoId), socialChatPresenca(person.alunoId)]); setMessages(nextMessages as Message[]); setOnline(nextOnline); } catch (error) { console.warn("[SocialChat] Falha ao carregar:", error); } }, [person]);
  useEffect(() => { if (!visible) return; setLoading(true); void load().finally(() => setLoading(false)); const timer = setInterval(() => void load(), 5000); return () => clearInterval(timer); }, [visible, load]);
  async function send() { if (!text.trim() || sending) return; setSending(true); try { await socialChatEnviar(person.alunoId, text); setText(""); await load(); } catch (error) { console.warn("[SocialChat] Falha ao enviar:", error); } finally { setSending(false); } }
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.backdrop}><View style={[s.modal, { backgroundColor: palette.surfaceElevated, borderColor: palette.border }]}><View style={[s.header, { borderBottomColor: palette.border }]}><View style={s.heading}><MaterialCommunityIcons name="account-circle-outline" size={25} color={accent} /><View><Text style={[s.title, { color: palette.text }]}>{person.apelido || person.nome}</Text><View style={s.onlineRow}><View style={[s.dot, { backgroundColor: online ? "#62db9b" : palette.textMuted }]} /><Text style={[s.subtitle, { color: palette.textMuted }]}>{online ? "online" : "offline"}</Text></View></View></View><Pressable onPress={onClose} accessibilityLabel="Fechar conversa"><Text style={[s.close, { color: palette.text }]}>×</Text></Pressable></View>{loading ? <ActivityIndicator color={accent} style={s.loader} /> : <ScrollView contentContainerStyle={s.messages}>{messages.length ? messages.map((message) => <View key={message.id} style={[s.message, { backgroundColor: palette.surface, borderColor: palette.border }]}><Text style={[s.author, { color: accent }]}>{message.remetente_nome}</Text><Text style={[s.body, { color: palette.text }]}>{message.texto}</Text></View>) : <Text style={[s.empty, { color: palette.textMuted }]}>Comece uma conversa privada.</Text>}</ScrollView>}<View style={[s.composer, { borderTopColor: palette.border }]}><TextInput value={text} onChangeText={setText} onSubmitEditing={() => void send()} returnKeyType="send" placeholder="Mensagem privada..." placeholderTextColor={palette.textMuted} style={[s.input, { color: palette.text, borderColor: palette.border }]} maxLength={500} /><Pressable disabled={!text.trim() || sending} onPress={() => void send()} style={[s.send, { backgroundColor: text.trim() && !sending ? accent : palette.borderStrong }]}><MaterialCommunityIcons name="send" size={18} color="#fff" /></Pressable></View></View></View></Modal>;
}
const s = StyleSheet.create({ backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,.78)" }, modal: { height: "72%", borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, overflow: "hidden" }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 16, borderBottomWidth: 1 }, heading: { flexDirection: "row", alignItems: "center", gap: 10 }, title: { fontFamily: FontFamily.poppinsExtraBold, fontSize: 17 }, subtitle: { fontFamily: FontFamily.interMedium, fontSize: 11 }, onlineRow: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 2 }, dot: { width: 7, height: 7, borderRadius: 4 }, close: { fontSize: 30 }, loader: { marginTop: 80 }, messages: { padding: 14, gap: 8, flexGrow: 1 }, empty: { textAlign: "center", marginTop: 90, fontFamily: FontFamily.interMedium }, message: { borderRadius: 12, borderWidth: 1, padding: 10, alignSelf: "stretch" }, author: { fontFamily: FontFamily.poppinsExtraBold, fontSize: 10 }, body: { fontFamily: FontFamily.interMedium, fontSize: 14, marginTop: 4 }, composer: { flexDirection: "row", gap: 8, padding: 10, borderTopWidth: 1 }, input: { flex: 1, minHeight: 38, borderWidth: 1, borderRadius: 9, paddingHorizontal: 10, fontFamily: FontFamily.interMedium }, send: { width: 38, borderRadius: 9, alignItems: "center", justifyContent: "center" } });
