import { MaterialCommunityIcons } from "@expo/vector-icons";
import React from "react";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import type { SocialPerson } from "@/services/social/socialModel";

type Props = { person: SocialPerson; accent: string; actionLabel?: string; onAction?: () => void; secondaryLabel?: string; onSecondary?: () => void; onPressProfile?: () => void; onPressChat?: () => void };
export function SocialPersonCard({ person, accent, actionLabel, onAction, secondaryLabel, onSecondary, onPressProfile, onPressChat }: Props) {
  const podeConversar = person.status === "friend" || person.status === "candidate";
  return <View style={s.card}><Pressable accessibilityRole="button" accessibilityLabel={`Abrir perfil de ${person.apelido || person.nome}`} onPress={onPressProfile} style={s.identity}><View style={[s.avatar, { borderColor: accent }]}>{person.fotoUrl ? <Image source={{ uri: person.fotoUrl }} style={s.avatarImage} /> : <MaterialCommunityIcons name="account" size={26} color={accent} />}</View><View style={s.info}><View style={s.nameRow}><Text style={s.name}>{person.apelido || person.nome}</Text><View accessibilityLabel={person.online ? "online" : "offline"} style={[s.statusDot, { backgroundColor: person.online ? "#62db9b" : "#68677c" }]} /></View><Text style={s.profile}>{person.perfilAtivo || "Perfil de jornada"}</Text>{person.guildaNome ? <Text style={s.guild}>{person.guildaNome}</Text> : null}</View></Pressable>{podeConversar ? <Pressable accessibilityRole="button" accessibilityLabel={`Conversar com ${person.apelido || person.nome}`} onPress={onPressChat ?? onPressProfile} style={s.chat}><MaterialCommunityIcons name="message-text-outline" size={18} color={accent} /></Pressable> : null}{secondaryLabel && onSecondary ? <Pressable accessibilityRole="button" onPress={onSecondary} style={s.secondary}><Text style={s.secondaryText}>{secondaryLabel}</Text></Pressable> : null}{actionLabel && onAction ? <Pressable accessibilityRole="button" onPress={onAction} style={[s.action, { backgroundColor: accent }]}><Text style={s.actionText}>{actionLabel}</Text></Pressable> : null}</View>;
}
const s = StyleSheet.create({ card: { flexDirection: "row", alignItems: "center", gap: 8, padding: 12, borderRadius: 12, backgroundColor: "rgba(242,247,250,.08)", marginBottom: 8 }, identity: { flex: 1, flexDirection: "row", alignItems: "center", gap: 10 }, avatar: { width: 44, height: 44, borderRadius: 22, borderWidth: 2, alignItems: "center", justifyContent: "center", overflow: "hidden" }, avatarImage: { width: "100%", height: "100%" }, info: { flex: 1 }, nameRow: { flexDirection: "row", alignItems: "center", gap: 6 }, name: { color: "#f2f7fa", fontSize: 15, fontWeight: "700" }, statusDot: { width: 8, height: 8, borderRadius: 4 }, profile: { color: "rgba(242,247,250,.62)", fontSize: 11, marginTop: 3 }, guild: { color: "#a9c5ff", fontSize: 10, marginTop: 3 }, chat: { padding: 7 }, action: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8 }, actionText: { color: "#fff", fontSize: 11, fontWeight: "800" }, secondary: { padding: 6 }, secondaryText: { color: "rgba(242,247,250,.62)", fontSize: 10 } });
