import { AchievementIcon, GuildIcon } from "@/assets/social/guild-icons";
import { carregarPerfilPublico } from "@/services/social/publicProfileService";
import { PrivateChatModal } from "@/components/social/PrivateChatModal";
import type { PublicProfile } from "@/services/social/publicProfileModel";
import { FontFamily } from "@/styles/GlobalStyle";
import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Image, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

type Props = { visible: boolean; alunoId: string | null; classeId: number; accent: string; online?: boolean; onClose: () => void };

export function SocialProfileModal({ visible, alunoId, classeId, accent, online = false, onClose }: Props) {
  const [profile, setProfile] = useState<PublicProfile | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const [privateChatVisible, setPrivateChatVisible] = useState(false);
  const load = useCallback(async () => { if (!alunoId) return; setLoading(true); setError(false); try { setProfile(await carregarPerfilPublico(alunoId, classeId)); } catch { setError(true); } finally { setLoading(false); } }, [alunoId, classeId]);
  useEffect(() => { if (visible) void load(); else setProfile(null); }, [visible, load]);
  return <><Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}><View style={s.backdrop}><View style={s.modal}><Pressable accessibilityRole="button" accessibilityLabel="Fechar perfil" onPress={onClose} style={s.close}><Text style={s.closeText}>×</Text></Pressable>{loading ? <ActivityIndicator color={accent} style={s.loader} /> : error ? <View style={s.center}><Text style={s.error}>Não foi possível carregar este perfil.</Text><Pressable onPress={() => void load()} style={[s.retry, { backgroundColor: accent }]}><Text style={s.retryText}>Tentar novamente</Text></Pressable></View> : profile ? <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}><View style={[s.banner, { backgroundColor: `${accent}35` }]}>{profile.bannerUrl ? <Image source={{ uri: profile.bannerUrl }} style={s.bannerImage} /> : <GuildIcon color={accent} size={54} />}</View><View style={[s.avatar, { borderColor: accent }]}>{profile.fotoUrl ? <Image source={{ uri: profile.fotoUrl }} style={s.avatarImage} /> : <Text style={[s.avatarLetter, { color: accent }]}>{profile.nome.slice(0, 1).toUpperCase()}</Text>}</View><View style={s.heading}><Text style={s.name}>{profile.nome.toUpperCase()}</Text>{profile.apelido ? <Text style={s.handle}>@{profile.apelido}</Text> : null}</View><View style={s.rule} />{profile.guilda ? <View style={s.guildRow}><GuildIcon color={accent} size={28} /><View><Text style={s.label}>GUILDA</Text><Text style={s.value}>{profile.guilda.nome} · {profile.guilda.membros} pessoas</Text></View></View> : null}<Text style={s.label}>DADOS</Text><Text style={s.value}>{profile.perfilAtivo || "Jornada ativa"}</Text>{profile.perfilDescricao ? <><Text style={s.label}>SOBRE O PERFIL</Text><Text style={s.value}>{profile.perfilDescricao}</Text></> : null}{profile.descricao ? <><Text style={s.label}>SOBRE</Text><Text style={s.value}>{profile.descricao}</Text></> : null}<View style={s.achievementsHeader}><Text style={s.label}>CONQUISTAS</Text><Text style={s.points}>{profile.pontosConquistas} pts</Text></View>{profile.conquistas.length === 0 ? <Text style={s.muted}>Nenhuma conquista pública ainda.</Text> : <View style={s.badges}>{profile.conquistas.map((achievement) => <View key={achievement.id} style={s.badge}><AchievementIcon color={accent} size={25} /><Text numberOfLines={2} style={s.badgeText}>{achievement.nome}</Text></View>)}</View>}<Pressable accessibilityRole="button" onPress={() => setPrivateChatVisible(true)} style={[s.chatButton, { borderColor: accent }]}><Text style={[s.chatButtonText, { color: accent }]}>Conversar em privado</Text></Pressable></ScrollView> : <View style={s.center}><Text style={s.error}>Perfil indisponível.</Text></View>}</View></View></Modal>{profile && alunoId ? <PrivateChatModal visible={privateChatVisible} person={{ alunoId, nome: profile.nome, apelido: profile.apelido, online: false }} accent={accent} onClose={() => setPrivateChatVisible(false)} /> : null}</>;
}

const s = StyleSheet.create({ backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,.72)" }, modal: { maxHeight: "92%", backgroundColor: "#11102d", borderTopLeftRadius: 24, borderTopRightRadius: 24, overflow: "hidden" }, close: { position: "absolute", zIndex: 2, right: 14, top: 8, width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 17, backgroundColor: "rgba(0,0,0,.45)" }, closeText: { color: "#fff", fontSize: 26, lineHeight: 28 }, scroll: { paddingBottom: 30 }, loader: { paddingVertical: 120 }, center: { minHeight: 300, alignItems: "center", justifyContent: "center", padding: 24, gap: 14 }, banner: { height: 138, alignItems: "center", justifyContent: "center" }, bannerImage: { width: "100%", height: "100%" }, avatar: { width: 82, height: 82, marginTop: -34, marginLeft: 24, borderRadius: 41, borderWidth: 5, backgroundColor: "#0b1730", alignItems: "center", justifyContent: "center", overflow: "hidden" }, avatarImage: { width: "100%", height: "100%" }, avatarLetter: { fontFamily: FontFamily.poppinsExtraBold, fontSize: 32 }, heading: { paddingHorizontal: 24, paddingTop: 10 }, name: { color: "#f3f6ff", fontFamily: FontFamily.inikaBold, fontSize: 16 }, handle: { color: "#a9a8bc", fontFamily: FontFamily.interMedium, marginTop: 3 }, rule: { height: 1, backgroundColor: "rgba(242,247,250,.5)", margin: 16 }, label: { color: "#f3f6ff", fontFamily: FontFamily.inikaBold, fontSize: 12, marginHorizontal: 24, marginTop: 16 }, value: { color: "#b9b7c7", fontFamily: FontFamily.interMedium, fontSize: 13, lineHeight: 20, marginHorizontal: 24, marginTop: 5 }, guildRow: { flexDirection: "row", alignItems: "center", gap: 10, marginHorizontal: 20, padding: 12, borderRadius: 12, backgroundColor: "rgba(157,184,255,.1)" }, achievementsHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 4 }, points: { color: "#f4cf75", marginRight: 24, marginTop: 16, fontWeight: "800" }, badges: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingHorizontal: 24, marginTop: 10 }, badge: { width: "31%", minHeight: 72, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(244,207,117,.09)", padding: 6 }, badgeText: { color: "#d7d4e2", fontSize: 10, textAlign: "center", marginTop: 4 }, chatButton: { marginHorizontal: 24, marginTop: 22, alignItems: "center", paddingVertical: 12, borderRadius: 10, borderWidth: 1 }, chatButtonText: { fontFamily: FontFamily.poppinsExtraBold }, muted: { color: "#8f8da3", marginHorizontal: 24, marginTop: 8 }, error: { color: "#c6c3d0", fontSize: 14, textAlign: "center" }, retry: { paddingHorizontal: 18, paddingVertical: 10, borderRadius: 9 }, retryText: { color: "#fff", fontWeight: "800" } });
